---
label: Catálogo
hide_body: false
fields:
- type: file
  name: thumbnail
  label: Thumbnail
  description: This will only show up on the front page
- type: text
  name: title
  label: Title
- type: datetime
  name: date
  label: Date
  config:
    required: true
    date_format: YYYY-MM-DD
    time_format: ''
    export_format: YYYY-MM-DD
    display_utc: true
  default: now
  hidden: false
- type: tag_list
  name: categories
  label: Categories
- type: text
  name: estado
  label: estado
- type: text
  name: Talla
  label: talla
- type: text
  name: Disponibilidad
  label: disponibilidad
- type: text
  name: compra_url
  label: compra_url
  config:
    required: true
pages:
- catalogo/bolso-de-mano-betseyville.md
